blank_issues_enabled: false
contact_links:
  - name: Pi-ware website
    url: https://github.com/oxmc/pi-ware/issues/new?title=Add%20this%20to%20the%20website
    about: Suggest/submit a change to the website.

